### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by snehmatic** [dosXdev/banQuest#9]

**Comment by CaptainIDB** [comment]
I have made the initial design for our resource management system, considering the growing demand and scalability requirements. After careful consideration, I’ve chosen to implement this system using a NoSQL database.




![Image](https://github.com/dosXdev/banQuest/assets/41210423/b174b591-a7cc-426a-a46f-8fc01b9c9a75)

**Comment by CaptainIDB** [comment]
DynamoDB (NoSQL) has been replaced by PostgreSQL, because of complexities with the Django backend.
Here's the updated Database Design.

![Image](https://github.com/dosXdev/banQuest/assets/41210423/26341f96-f210-487b-a52a-92bb2efed9cd)
